all:
  children:
    sites:
      children:
        site_site_a:
          hosts:
            rhel9-app-a1:
            rhel7-db-a1:
        site_site_b:
          hosts:
            deb12-web-b1:
            centos7-app-b1:

    environment_type_dev:
      hosts:
        rhel9-app-a1:
    environment_type_prod_standard:
      hosts:
        deb12-web-b1:
    environment_type_prod_critical:
      hosts:
        rhel7-db-a1:
        centos7-app-b1:

    resource_class_app:
      hosts:
        rhel9-app-a1:
        centos7-app-b1:
    resource_class_db:
      hosts:
        rhel7-db-a1:
    resource_class_web:
      hosts:
        deb12-web-b1:
